package terminology

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"regexp"
	"strings"
)

var tableNameSanitizer = regexp.MustCompile(`[^a-z0-9_]+`)

// SQLiteModTermStore implements ModTermStore using terminology.db.
type SQLiteModTermStore struct {
	db     *sql.DB
	logger *slog.Logger
}

// NewSQLiteModTermStore creates a new SQLiteModTermStore.
func NewSQLiteModTermStore(db *sql.DB, logger *slog.Logger) *SQLiteModTermStore {
	return &SQLiteModTermStore{
		db:     db,
		logger: logger.With("component", "SQLiteModTermStore"),
	}
}

// InitSchema creates shared summary tables for terminology.db.
func (s *SQLiteModTermStore) InitSchema(ctx context.Context) error {
	queries := []string{
		`CREATE TABLE IF NOT EXISTS terminology_phase_summary (
			task_id TEXT PRIMARY KEY,
			status TEXT NOT NULL,
			target_count INTEGER NOT NULL DEFAULT 0,
			saved_count INTEGER NOT NULL DEFAULT 0,
			failed_count INTEGER NOT NULL DEFAULT 0
		);`,
	}
	for _, query := range queries {
		if _, err := s.db.ExecContext(ctx, query); err != nil {
			return fmt.Errorf("init terminology schema: %w", err)
		}
	}
	return nil
}

// SaveTerms inserts translated terms into source-file scoped tables.
func (s *SQLiteModTermStore) SaveTerms(ctx context.Context, results []TermTranslationResult) error {
	if len(results) == 0 {
		return nil
	}
	if err := s.InitSchema(ctx); err != nil {
		return fmt.Errorf("init terminology schema before save: %w", err)
	}

	grouped := make(map[string][]TermTranslationResult)
	for _, result := range results {
		tableName := modTableName(result.SourceFile)
		grouped[tableName] = append(grouped[tableName], result)
	}
	for tableName, group := range grouped {
		if err := s.ensureModTable(ctx, tableName); err != nil {
			return fmt.Errorf("ensure terminology table table=%s: %w", tableName, err)
		}
		if err := s.upsertTerms(ctx, tableName, group); err != nil {
			return fmt.Errorf("upsert terminology table table=%s: %w", tableName, err)
		}
	}
	return nil
}

// GetTerm retrieves a translation by scanning source-file tables.
func (s *SQLiteModTermStore) GetTerm(ctx context.Context, originalEN string) (string, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'mod_terms_%' ORDER BY name`)
	if err != nil {
		return "", fmt.Errorf("list terminology tables: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			return "", fmt.Errorf("scan terminology table name: %w", err)
		}
		if err := validateModTableName(tableName); err != nil {
			return "", fmt.Errorf("validate terminology table name table=%s: %w", tableName, err)
		}
		//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
		query := fmt.Sprintf("SELECT translated_ja FROM %s WHERE original_en = ? LIMIT 1", tableName)
		var translated string
		err := s.db.QueryRowContext(ctx, query, originalEN).Scan(&translated)
		if err == nil {
			return translated, nil
		}
		if err != nil && err != sql.ErrNoRows {
			return "", fmt.Errorf("query terminology table table=%s: %w", tableName, err)
		}
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate terminology tables: %w", err)
	}
	return "", nil
}

// Clear removes all source-file terminology tables and summary rows.
func (s *SQLiteModTermStore) Clear(ctx context.Context) error {
	rows, err := s.db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'mod_terms_%' ORDER BY name`)
	if err != nil {
		return fmt.Errorf("list terminology tables for clear: %w", err)
	}
	defer rows.Close()

	names := make([]string, 0)
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return fmt.Errorf("scan terminology clear table name: %w", err)
		}
		names = append(names, name)
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate terminology clear table names: %w", err)
	}
	for _, name := range names {
		if err := validateModTableName(name); err != nil {
			return fmt.Errorf("validate terminology clear table name table=%s: %w", name, err)
		}
		//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
		if _, err := s.db.ExecContext(ctx, fmt.Sprintf("DROP TABLE IF EXISTS %s", name)); err != nil {
			return fmt.Errorf("drop terminology table table=%s: %w", name, err)
		}
	}
	if _, err := s.db.ExecContext(ctx, `DELETE FROM terminology_phase_summary`); err != nil {
		return fmt.Errorf("clear terminology phase summary: %w", err)
	}
	return nil
}

// UpdatePhaseSummary upserts one task-scoped summary row.
func (s *SQLiteModTermStore) UpdatePhaseSummary(ctx context.Context, summary PhaseSummary) error {
	if err := s.InitSchema(ctx); err != nil {
		return fmt.Errorf("init terminology schema before phase summary update: %w", err)
	}
	if _, err := s.db.ExecContext(ctx, `
		INSERT INTO terminology_phase_summary (task_id, status, target_count, saved_count, failed_count)
		VALUES (?, ?, ?, ?, ?)
		ON CONFLICT(task_id) DO UPDATE SET
			status = excluded.status,
			target_count = excluded.target_count,
			saved_count = excluded.saved_count,
			failed_count = excluded.failed_count
	`, summary.TaskID, summary.Status, summary.TargetCount, summary.SavedCount, summary.FailedCount); err != nil {
		return fmt.Errorf("upsert terminology phase summary task_id=%s: %w", summary.TaskID, err)
	}
	return nil
}

// GetPhaseSummary returns one task-scoped terminology phase summary.
func (s *SQLiteModTermStore) GetPhaseSummary(ctx context.Context, taskID string) (PhaseSummary, error) {
	if err := s.InitSchema(ctx); err != nil {
		return PhaseSummary{}, fmt.Errorf("init terminology schema before phase summary read: %w", err)
	}
	summary := PhaseSummary{TaskID: taskID, Status: "pending"}
	err := s.db.QueryRowContext(ctx, `
		SELECT status, target_count, saved_count, failed_count
		FROM terminology_phase_summary
		WHERE task_id = ?
	`, taskID).Scan(&summary.Status, &summary.TargetCount, &summary.SavedCount, &summary.FailedCount)
	if err == sql.ErrNoRows {
		return summary, nil
	}
	if err != nil {
		return PhaseSummary{}, fmt.Errorf("query terminology phase summary task_id=%s: %w", taskID, err)
	}
	return summary, nil
}

func (s *SQLiteModTermStore) ensureModTable(ctx context.Context, tableName string) error {
	if err := validateModTableName(tableName); err != nil {
		return fmt.Errorf("validate mod table name: %w", err)
	}
	//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
	query := fmt.Sprintf(`
		CREATE TABLE IF NOT EXISTS %s (
			original_en TEXT NOT NULL,
			record_type TEXT NOT NULL,
			translated_ja TEXT NOT NULL,
			status TEXT NOT NULL,
			editor_id TEXT,
			source_plugin TEXT,
			source_file TEXT,
			error_message TEXT,
			PRIMARY KEY (original_en, record_type)
		)
	`, tableName)
	if _, err := s.db.ExecContext(ctx, query); err != nil {
		return fmt.Errorf("create terminology mod table table=%s: %w", tableName, err)
	}
	return nil
}

func (s *SQLiteModTermStore) upsertTerms(ctx context.Context, tableName string, results []TermTranslationResult) error {
	if err := validateModTableName(tableName); err != nil {
		return fmt.Errorf("validate mod table name: %w", err)
	}
	//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
	query := fmt.Sprintf(`
		INSERT INTO %s (
			original_en, record_type, translated_ja, status, editor_id, source_plugin, source_file, error_message
		)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(original_en, record_type) DO UPDATE SET
			translated_ja = excluded.translated_ja,
			status = excluded.status,
			editor_id = excluded.editor_id,
			source_plugin = excluded.source_plugin,
			source_file = excluded.source_file,
			error_message = excluded.error_message
	`, tableName)

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin terminology table upsert table=%s: %w", tableName, err)
	}
	defer func() {
		_ = tx.Rollback()
	}()

	stmt, err := tx.PrepareContext(ctx, query)
	if err != nil {
		return fmt.Errorf("prepare terminology upsert table=%s: %w", tableName, err)
	}
	defer stmt.Close()

	for _, result := range results {
		if _, err := stmt.ExecContext(
			ctx,
			result.SourceText,
			result.RecordType,
			result.TranslatedText,
			result.Status,
			result.EditorID,
			result.SourcePlugin,
			result.SourceFile,
			result.ErrorMessage,
		); err != nil {
			return fmt.Errorf("execute terminology upsert table=%s source=%s: %w", tableName, result.SourceText, err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit terminology upsert table=%s: %w", tableName, err)
	}
	return nil
}

func modTableName(sourceFile string) string {
	base := strings.ToLower(strings.TrimSpace(sourceFile))
	base = strings.TrimSuffix(base, ".json")
	base = tableNameSanitizer.ReplaceAllString(base, "_")
	base = strings.Trim(base, "_")
	if base == "" {
		base = "default"
	}
	return "mod_terms_" + base
}

func validateModTableName(tableName string) error {
	if !strings.HasPrefix(tableName, "mod_terms_") {
		return fmt.Errorf("unexpected prefix")
	}
	if tableNameSanitizer.ReplaceAllString(tableName, "") != tableName {
		return fmt.Errorf("table name contains invalid characters")
	}
	return nil
}
