package terminology

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"regexp"
	"strings"
)

var tableNameSanitizer = regexp.MustCompile(`[^a-z0-9_]+`)

// SQLiteModTermStore implements ModTermStore using terminology.db.
type SQLiteModTermStore struct {
	db     *sql.DB
	logger *slog.Logger
}

// NewSQLiteModTermStore creates a new SQLiteModTermStore.
func NewSQLiteModTermStore(db *sql.DB, logger *slog.Logger) *SQLiteModTermStore {
	return &SQLiteModTermStore{
		db:     db,
		logger: logger.With("component", "SQLiteModTermStore"),
	}
}

// InitSchema creates shared summary tables for terminology.db.
func (s *SQLiteModTermStore) InitSchema(ctx context.Context) error {
	queries := []string{
		`CREATE TABLE IF NOT EXISTS terminology_phase_summary (
			task_id TEXT PRIMARY KEY,
			status TEXT NOT NULL,
			target_count INTEGER NOT NULL DEFAULT 0,
			saved_count INTEGER NOT NULL DEFAULT 0,
			failed_count INTEGER NOT NULL DEFAULT 0,
			progress_mode TEXT NOT NULL DEFAULT 'hidden',
			progress_current INTEGER NOT NULL DEFAULT 0,
			progress_total INTEGER NOT NULL DEFAULT 0,
			progress_message TEXT NOT NULL DEFAULT ''
		);`,
	}
	for _, query := range queries {
		if _, err := s.db.ExecContext(ctx, query); err != nil {
			return fmt.Errorf("init terminology schema: %w", err)
		}
	}
	if err := s.ensurePhaseSummaryColumns(ctx); err != nil {
		return fmt.Errorf("ensure terminology phase summary columns: %w", err)
	}
	return nil
}

// SaveTerms inserts translated terms into source-file scoped tables.
func (s *SQLiteModTermStore) SaveTerms(ctx context.Context, results []TermTranslationResult) error {
	if len(results) == 0 {
		return nil
	}
	if err := s.InitSchema(ctx); err != nil {
		return fmt.Errorf("init terminology schema before save: %w", err)
	}

	grouped := make(map[string][]TermTranslationResult)
	for _, result := range results {
		tableName := modTableName(result.SourceFile)
		grouped[tableName] = append(grouped[tableName], result)
	}
	for tableName, group := range grouped {
		if err := s.ensureModTable(ctx, tableName); err != nil {
			return fmt.Errorf("ensure terminology table table=%s: %w", tableName, err)
		}
		if err := s.upsertTerms(ctx, tableName, group); err != nil {
			return fmt.Errorf("upsert terminology table table=%s: %w", tableName, err)
		}
	}
	return nil
}

// GetTerm retrieves a translation by scanning source-file tables.
func (s *SQLiteModTermStore) GetTerm(ctx context.Context, originalEN string) (string, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'mod_terms_%' ORDER BY name`)
	if err != nil {
		return "", fmt.Errorf("list terminology tables: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			return "", fmt.Errorf("scan terminology table name: %w", err)
		}
		if err := validateModTableName(tableName); err != nil {
			return "", fmt.Errorf("validate terminology table name table=%s: %w", tableName, err)
		}
		//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
		query := fmt.Sprintf("SELECT translated_ja FROM %s WHERE original_en = ? LIMIT 1", tableName)
		var translated string
		err := s.db.QueryRowContext(ctx, query, originalEN).Scan(&translated)
		if err == nil {
			return translated, nil
		}
		if err != nil && err != sql.ErrNoRows {
			return "", fmt.Errorf("query terminology table table=%s: %w", tableName, err)
		}
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate terminology tables: %w", err)
	}
	return "", nil
}

// Clear removes all source-file terminology tables and summary rows.
func (s *SQLiteModTermStore) Clear(ctx context.Context) error {
	rows, err := s.db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'mod_terms_%' ORDER BY name`)
	if err != nil {
		return fmt.Errorf("list terminology tables for clear: %w", err)
	}
	defer rows.Close()

	names := make([]string, 0)
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return fmt.Errorf("scan terminology clear table name: %w", err)
		}
		names = append(names, name)
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate terminology clear table names: %w", err)
	}
	for _, name := range names {
		if err := validateModTableName(name); err != nil {
			return fmt.Errorf("validate terminology clear table name table=%s: %w", name, err)
		}
		//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
		if _, err := s.db.ExecContext(ctx, fmt.Sprintf("DROP TABLE IF EXISTS %s", name)); err != nil {
			return fmt.Errorf("drop terminology table table=%s: %w", name, err)
		}
	}
	if _, err := s.db.ExecContext(ctx, `DELETE FROM terminology_phase_summary`); err != nil {
		return fmt.Errorf("clear terminology phase summary: %w", err)
	}
	return nil
}

// UpdatePhaseSummary upserts one task-scoped summary row.
func (s *SQLiteModTermStore) UpdatePhaseSummary(ctx context.Context, summary PhaseSummary) error {
	if err := s.InitSchema(ctx); err != nil {
		return fmt.Errorf("init terminology schema before phase summary update: %w", err)
	}
	if _, err := s.db.ExecContext(ctx, `
		INSERT INTO terminology_phase_summary (
			task_id, status, target_count, saved_count, failed_count, progress_mode, progress_current, progress_total, progress_message
		)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(task_id) DO UPDATE SET
			status = excluded.status,
			target_count = excluded.target_count,
			saved_count = excluded.saved_count,
			failed_count = excluded.failed_count,
			progress_mode = excluded.progress_mode,
			progress_current = excluded.progress_current,
			progress_total = excluded.progress_total,
			progress_message = excluded.progress_message
	`, summary.TaskID, summary.Status, summary.TargetCount, summary.SavedCount, summary.FailedCount, summary.ProgressMode, summary.ProgressCurrent, summary.ProgressTotal, summary.ProgressMessage); err != nil {
		return fmt.Errorf("upsert terminology phase summary task_id=%s: %w", summary.TaskID, err)
	}
	return nil
}

// GetPhaseSummary returns one task-scoped terminology phase summary.
func (s *SQLiteModTermStore) GetPhaseSummary(ctx context.Context, taskID string) (PhaseSummary, error) {
	if err := s.InitSchema(ctx); err != nil {
		return PhaseSummary{}, fmt.Errorf("init terminology schema before phase summary read: %w", err)
	}
	summary := PhaseSummary{TaskID: taskID, Status: "pending", ProgressMode: "hidden"}
	err := s.db.QueryRowContext(ctx, `
		SELECT status, target_count, saved_count, failed_count, progress_mode, progress_current, progress_total, progress_message
		FROM terminology_phase_summary
		WHERE task_id = ?
	`, taskID).Scan(
		&summary.Status,
		&summary.TargetCount,
		&summary.SavedCount,
		&summary.FailedCount,
		&summary.ProgressMode,
		&summary.ProgressCurrent,
		&summary.ProgressTotal,
		&summary.ProgressMessage,
	)
	if err == sql.ErrNoRows {
		return summary, nil
	}
	if err != nil {
		return PhaseSummary{}, fmt.Errorf("query terminology phase summary task_id=%s: %w", taskID, err)
	}
	return summary, nil
}

// GetPreviewTranslations returns translated text keyed by preview row ID.
func (s *SQLiteModTermStore) GetPreviewTranslations(ctx context.Context, entries []TerminologyEntry) (map[string]PreviewTranslation, error) {
	translations := make(map[string]PreviewTranslation, len(entries))
	for _, entry := range entries {
		translations[entry.ID] = PreviewTranslation{
			RowID:            entry.ID,
			TranslationState: "missing",
		}

		tableName := modTableName(entry.SourceFile)
		if err := validateModTableName(tableName); err != nil {
			return nil, fmt.Errorf("validate preview translation table table=%s: %w", tableName, err)
		}
		//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
		query := fmt.Sprintf("SELECT translated_ja, status FROM %s WHERE original_en = ? AND record_type = ? LIMIT 1", tableName)

		var translatedText string
		var status string
		err := s.db.QueryRowContext(ctx, query, entry.SourceText, entry.RecordType).Scan(&translatedText, &status)
		if err == sql.ErrNoRows {
			translatedText, translationState, fallbackErr := s.lookupPreviewTranslationFallback(ctx, entry)
			if fallbackErr != nil {
				return nil, fallbackErr
			}
			if translationState == "missing" {
				continue
			}
			translations[entry.ID] = PreviewTranslation{
				RowID:            entry.ID,
				TranslatedText:   translatedText,
				TranslationState: translationState,
			}
			continue
		}
		if err != nil {
			if strings.Contains(err.Error(), "no such table") {
				translatedText, translationState, fallbackErr := s.lookupPreviewTranslationFallback(ctx, entry)
				if fallbackErr != nil {
					return nil, fallbackErr
				}
				if translationState == "missing" {
					continue
				}
				translations[entry.ID] = PreviewTranslation{
					RowID:            entry.ID,
					TranslatedText:   translatedText,
					TranslationState: translationState,
				}
				continue
			}
			return nil, fmt.Errorf("query preview translation row_id=%s: %w", entry.ID, err)
		}

		translationState := "missing"
		if strings.TrimSpace(translatedText) != "" && status != "error" {
			translationState = "translated"
		}
		translations[entry.ID] = PreviewTranslation{
			RowID:            entry.ID,
			TranslatedText:   translatedText,
			TranslationState: translationState,
		}
	}
	return translations, nil
}

func (s *SQLiteModTermStore) lookupPreviewTranslationFallback(ctx context.Context, entry TerminologyEntry) (string, string, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'mod_terms_%' ORDER BY name`)
	if err != nil {
		return "", "", fmt.Errorf("list terminology tables for preview fallback: %w", err)
	}
	tableNames := make([]string, 0)

	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			_ = rows.Close()
			return "", "", fmt.Errorf("scan preview fallback table name: %w", err)
		}
		if err := validateModTableName(tableName); err != nil {
			_ = rows.Close()
			return "", "", fmt.Errorf("validate preview fallback table=%s: %w", tableName, err)
		}
		tableNames = append(tableNames, tableName)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return "", "", fmt.Errorf("iterate preview fallback tables: %w", err)
	}
	if err := rows.Close(); err != nil {
		return "", "", fmt.Errorf("close preview fallback table rows: %w", err)
	}

	for _, tableName := range tableNames {
		//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
		query := fmt.Sprintf("SELECT translated_ja, status FROM %s WHERE original_en = ? AND record_type = ? LIMIT 1", tableName)
		var translatedText string
		var status string
		err := s.db.QueryRowContext(ctx, query, entry.SourceText, entry.RecordType).Scan(&translatedText, &status)
		if err == sql.ErrNoRows {
			continue
		}
		if err != nil {
			return "", "", fmt.Errorf("query preview fallback row_id=%s: %w", entry.ID, err)
		}
		if strings.TrimSpace(translatedText) == "" || status == "error" {
			return "", "missing", nil
		}
		return translatedText, "translated", nil
	}
	return "", "missing", nil
}

func (s *SQLiteModTermStore) ensurePhaseSummaryColumns(ctx context.Context) error {
	rows, err := s.db.QueryContext(ctx, `PRAGMA table_info(terminology_phase_summary)`)
	if err != nil {
		return fmt.Errorf("pragma terminology_phase_summary: %w", err)
	}
	defer rows.Close()

	columns := map[string]bool{}
	for rows.Next() {
		var (
			cid        int
			name       string
			dataType   string
			notNull    int
			defaultVal sql.NullString
			pk         int
		)
		if err := rows.Scan(&cid, &name, &dataType, &notNull, &defaultVal, &pk); err != nil {
			return fmt.Errorf("scan terminology_phase_summary columns: %w", err)
		}
		columns[name] = true
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate terminology_phase_summary columns: %w", err)
	}

	alterStatements := []struct {
		column string
		query  string
	}{
		{column: "progress_mode", query: `ALTER TABLE terminology_phase_summary ADD COLUMN progress_mode TEXT NOT NULL DEFAULT 'hidden'`},
		{column: "progress_current", query: `ALTER TABLE terminology_phase_summary ADD COLUMN progress_current INTEGER NOT NULL DEFAULT 0`},
		{column: "progress_total", query: `ALTER TABLE terminology_phase_summary ADD COLUMN progress_total INTEGER NOT NULL DEFAULT 0`},
		{column: "progress_message", query: `ALTER TABLE terminology_phase_summary ADD COLUMN progress_message TEXT NOT NULL DEFAULT ''`},
	}
	for _, stmt := range alterStatements {
		if columns[stmt.column] {
			continue
		}
		if _, err := s.db.ExecContext(ctx, stmt.query); err != nil {
			return fmt.Errorf("add terminology_phase_summary column %s: %w", stmt.column, err)
		}
	}
	return nil
}

func (s *SQLiteModTermStore) ensureModTable(ctx context.Context, tableName string) error {
	if err := validateModTableName(tableName); err != nil {
		return fmt.Errorf("validate mod table name: %w", err)
	}
	//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
	query := fmt.Sprintf(`
		CREATE TABLE IF NOT EXISTS %s (
			original_en TEXT NOT NULL,
			record_type TEXT NOT NULL,
			translated_ja TEXT NOT NULL,
			status TEXT NOT NULL,
			editor_id TEXT,
			source_plugin TEXT,
			source_file TEXT,
			error_message TEXT,
			PRIMARY KEY (original_en, record_type)
		)
	`, tableName)
	if _, err := s.db.ExecContext(ctx, query); err != nil {
		return fmt.Errorf("create terminology mod table table=%s: %w", tableName, err)
	}
	return nil
}

func (s *SQLiteModTermStore) upsertTerms(ctx context.Context, tableName string, results []TermTranslationResult) error {
	if err := validateModTableName(tableName); err != nil {
		return fmt.Errorf("validate mod table name: %w", err)
	}
	//nolint:gosec // tableName is restricted by validateModTableName and generated by modTableName.
	query := fmt.Sprintf(`
		INSERT INTO %s (
			original_en, record_type, translated_ja, status, editor_id, source_plugin, source_file, error_message
		)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(original_en, record_type) DO UPDATE SET
			translated_ja = excluded.translated_ja,
			status = excluded.status,
			editor_id = excluded.editor_id,
			source_plugin = excluded.source_plugin,
			source_file = excluded.source_file,
			error_message = excluded.error_message
	`, tableName)

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin terminology table upsert table=%s: %w", tableName, err)
	}
	defer func() {
		_ = tx.Rollback()
	}()

	stmt, err := tx.PrepareContext(ctx, query)
	if err != nil {
		return fmt.Errorf("prepare terminology upsert table=%s: %w", tableName, err)
	}
	defer stmt.Close()

	for _, result := range results {
		if _, err := stmt.ExecContext(
			ctx,
			result.SourceText,
			result.RecordType,
			result.TranslatedText,
			result.Status,
			result.EditorID,
			result.SourcePlugin,
			result.SourceFile,
			result.ErrorMessage,
		); err != nil {
			return fmt.Errorf("execute terminology upsert table=%s source=%s: %w", tableName, result.SourceText, err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit terminology upsert table=%s: %w", tableName, err)
	}
	return nil
}

func modTableName(sourceFile string) string {
	base := strings.ToLower(strings.TrimSpace(sourceFile))
	base = strings.TrimSuffix(base, ".json")
	base = tableNameSanitizer.ReplaceAllString(base, "_")
	base = strings.Trim(base, "_")
	if base == "" {
		base = "default"
	}
	return "mod_terms_" + base
}

func validateModTableName(tableName string) error {
	if !strings.HasPrefix(tableName, "mod_terms_") {
		return fmt.Errorf("unexpected prefix")
	}
	if tableNameSanitizer.ReplaceAllString(tableName, "") != tableName {
		return fmt.Errorf("table name contains invalid characters")
	}
	return nil
}
