package context_engine

import (
	"github.com/ishibata91/ai-translation-engine-2/pkg/domain/models"
)

// ContextEngine builds structured TranslationRequests from ExtractedData.
// It integrates dialogue tree analysis, speaker profiling, reference term lookup,
// and summary lookup to produce context-rich translation requests for Pass 2.
type ContextEngine interface {
	BuildTranslationRequests(data *models.ExtractedData, config ContextEngineConfig) ([]TranslationRequest, error)
}

// ToneResolver generates a tone instruction string from NPC attributes.
type ToneResolver interface {
	Resolve(race string, voiceType string, sex string) string
}

// PersonaLookup searches for an NPC's persona text by speaker ID.
type PersonaLookup interface {
	FindBySpeakerID(speakerID string) (*string, error)
}

// TermLookup searches dictionary and Mod term databases for reference terms
// related to the source text, and determines forced translation when applicable.
type TermLookup interface {
	// Search returns reference terms and an optional forced translation (on exact full-text match).
	Search(sourceText string) ([]ReferenceTerm, *string, error)
}

// SummaryLookup retrieves cached summaries generated by the Summary Generator Slice.
type SummaryLookup interface {
	FindDialogueSummary(dialogueGroupID string) (*string, error)
	FindQuestSummary(questID string) (*string, error)
}
