// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/ishibata91/ai-translation-engine-2/pkg/dictionary_builder"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func initializeImporter(db *sql.DB) dictionary_builder.DictionaryImporter {
	config := dictionary_builder.ConfigProvider()
	dictionaryStore := dictionary_builder.NewDictionaryStore(db)
	dictionaryImporter := dictionary_builder.NewImporter(config, dictionaryStore)
	return dictionaryImporter
}
