run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - revive
    - staticcheck

formatters:
  enable:
    - gofmt

linters-settings:
  revive:
    rules:
      - name: context-as-argument
      - name: empty-block
      - name: errorf
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: superfluous-else
      - name: unexported-return
      - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
