// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	parser2 "github.com/ishibata91/ai-translation-engine-2/pkg/slice/parser"
)

// Injectors from wire.go:

// InitializeParser creates a new Parser instance with all dependencies wired.
func InitializeParser(ctx context.Context) (parser2.Parser, func(), error) {
	parserParser := parser2.ProvideParser()
	return parserParser, func() {}, nil
}
