// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ishibata91/ai-translation-engine-2/pkg/config"
	"github.com/ishibata91/ai-translation-engine-2/pkg/infrastructure/database"
	"github.com/ishibata91/ai-translation-engine-2/pkg/infrastructure/logger"
	"github.com/ishibata91/ai-translation-engine-2/pkg/parser"
)

// Injectors from wire.go:

// InitializeParser creates a new Parser instance with all dependencies wired.
func InitializeParser(ctx context.Context) (parser.Parser, func(), error) {
	db, cleanup, err := database.NewSQLiteDB()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.ProvideLogger()
	sqLiteStore, err := config.NewSQLiteStore(ctx, db, slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	parserParser := parser.ProvideParser(sqLiteStore)
	return parserParser, func() {
		cleanup()
	}, nil
}
