// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package summary

import (
	"database/sql"
	"github.com/google/wire"
)

// Injectors from provider.go:

// To be used by the main wire.go if needed, or by testing.
func InitializeGenerator(db *sql.DB, config SummaryConfig) (Summary, error) {
	summarySummaryStore := NewSummaryStore(db)
	summary := NewSummaryGenerator(summarySummaryStore, config)
	return summary, nil
}

// provider.go:

// ProviderSet is the Wire provider set for the summary slice.
var ProviderSet = wire.NewSet(
	NewSummaryStore,
	NewSummaryGenerator,
)
