// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/ishibata91/ai-translation-engine-2/pkg/dictionary"
	"github.com/ishibata91/ai-translation-engine-2/pkg/infrastructure/logger"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func initializeImporter(db *sql.DB) dictionary.DictionaryImporter {
	config := dictionary.ConfigProvider()
	dictionaryStore := dictionary.NewDictionaryStore(db)
	slogLogger := logger.ProvideLogger()
	dictionaryImporter := dictionary.NewImporter(config, dictionaryStore, slogLogger)
	return dictionaryImporter
}
