// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ishibata91/ai-translation-engine-2/pkg/contract"
	"github.com/ishibata91/ai-translation-engine-2/pkg/loader"
)

// Injectors from wire.go:

// InitializeLoader creates a new Loader instance with all dependencies wired.
func InitializeLoader() contract.Loader {
	contractLoader := loader.ProvideLoader()
	return contractLoader
}
